### ISSUE TITLE
Retry when lost connection

### ISSUE THREAD

**Issue by creadone** [j8r/pool.cr#1]
Hi Julien,

To ensure the recovery of the connection between microservices (in different clouds) I started writing a simple shard [Cocoon](https://github.com/creadone/cocoon).

The main goal is to carefully handle disconnect and return non-blocking responses to prevent data loss: if the Queue,  Database or API is not available then save them locally for future delivery after connection recovery.

Today I found your shard and related discussion on the forum. Could you say about retry logic: you are planning to implement retries or shard will stay clear resources holder?

**Comment by j8r** [comment]
I guess the retry will be done in case of an `Exception`? I've not a strong opinion on this. For me, it is easy enough to implement this logic outside the pool: and will be much more flexible. For example, how many retries, in case of which exception(s).

Being a common use-case, we can add an example of how to do it in this repository.

Here is simple one:
```cr
pool = Pool.new { IO::Memory.new }

3.times do |i|
  resource = pool.get
  # do something, break will be executed if no exception has been raised
  break
rescue ex
  # log and continue the loop
  puts "Got #{ex} (try #{i})"
else
  pool.add resource
end
```

**Comment by j8r** [comment]
I suppose the retry will be done in case of an `Exception`? I've not a strong opinion on this. For me, it is easy enough to implement this logic outside the pool, and will be much more flexible. For example, how many retries, in case of which exception(s), keep the resource or try another one from the pool, etc.

Being a common use-case, we can add an example of how to do it in this repository.

Here is a simple one:
```cr
pool = Pool.new { IO::Memory.new }

3.times do |i|
  resource = pool.get
  # do something
rescue ex
  # log and continue the loop
  puts "Got #{ex} (try #{i})"
else
  pool.add resource
  break
end
```

**Comment by creadone** [comment]
Yes, you're right. Exponential backoff, app or networks exception, finite or endless retries... Retry logic is difficult to generalize into one or two use-cases. I didn't think about it right away.

Thanks for your time!
